### ISSUE TITLE
ローカルストレージ依存の設定をワンボタンでサーバーに（から）バックアップ（復元）する機能

### ISSUE THREAD

**Issue by waonme** [totegamma/concurrent-web#128]

**Comment by totegamma** [comment]
concurrent(バックエンド)のユーザーKVS機能の実装待ちですね(俺)

まずは今ユーザー設定がそれぞれ別の変数になっているのを、1つや用途別でくくって構造体として定義しておくと、バックエンドが対応したときにすぐ実装できるかもしれません。

**Comment by totegamma** [comment]
UserKV実装しました。
/api/v1/kv/:key へのGET/PUTで任意の値が読み書きできる。
これをつかったら設定のシンク作れそう～～～
