### ISSUE TITLE
投稿欄に入力中の文字列を特別な操作なしに記憶する機能

### ISSUE THREAD

**Issue by waonme** [totegamma/concurrent-web#130]
メディア機能が実装されるならそれも含めて記憶したい。
Misskeyのような感じ。

記憶内容をワンタップですべて消す機能も必要。

**Comment by totegamma** [comment]
> 記憶内容をワンタップですべて消す機能も必要。
それそれそれそれそれそれそれそれ

**Comment by totegamma** [comment]
https://notistack.com/features/basic
消したときにこれのActionsを使って
「消去しました [Undo]」みたいなsnack barを出してあげるとよさそう
