### ISSUE TITLE
フォルダ単位でストリームを見たい

### ISSUE THREAD

**Issue by waonme** [totegamma/concurrent-web#170]

**Comment by totegamma** [comment]
例えば、現状 https://develop.d3oazz131qdsmc.amplifyapp.com/#chrmsgep9dcl7anfkgcg@concurrent-dev.house.gammalab.net,chulj2up9dcvt9v9l2g0@concurrent-dev.house.gammalab.net
のリンクでGeneralと開発部お知らせのストリームを閲覧できる
フォルダ単位でストリームを見る場合もこの方法で複数ストリームを閲覧できるようにすると思うが、現状はヘッダーのタイトルが「GENERAL, 開発部お知らせ」と列挙されるようになってしまうが、フォルダ名がここに表示されるようにしたい。

方法としては2つあって、
1. リストとして一致するフォルダ名を探索し、表示する
2. ハッシュパラメーターに「alias」パラメーターを付与する

1の方法は作るのと計算が大変かも
2の方法は楽だしそのままリンクが他の人と共有できるポテンシャルも秘めているけれど、クエリにあるのがstreamのリストなのか他のパラメーターなのかを判断する方法がない(本当は、/#stream=aaa,bbb,ccc&alias=dddってしたいが、すでに/#aaa,bbb,cccというフォーマットを取ってしまっているためそこから変更する必要がある)

個人的には今後の拡張性もとって2の方法でいきたい
