### ISSUE TITLE
 Streamのリストがはみ出る

### ISSUE THREAD

**Issue by rassi0429** [totegamma/concurrent-web#24]
🥰 Expected Behavior
Streamのリストがはみ出ない
🤬 Actual Behavior
Streamのリストがはみ出る

**Comment by rassi0429** [comment]
![image](https://user-images.githubusercontent.com/91118218/236374830-59bb3b02-4466-4a3e-972b-5cb706297836.png)

**Comment by totegamma** [comment]
画面が細くなった時の問題であれば、#18 で自動的に解決されるかも？

**Comment by rassi0429** [comment]
まあおまかんの話かもしれませんが、単純に高さが足りないとbackgroundをはみ出してしまうようです。
解決策としては
- スクロールする
- backgroundを広げる(fixedにしてもいい)
斗思います
![image](https://user-images.githubusercontent.com/91118218/236375401-2c4f7b73-cb3e-4715-8fce-4a5e357b1e10.png)

**Comment by totegamma** [comment]
そういうことか！stream一覧のとこはスクロール入れたい

**Comment by rassi0429** [comment]
了解しました
