### ISSUE TITLE
ホーム同時投稿モードがOFFかつ投稿先が未指定の状態でPOSTすると、実際には投稿されずに投稿内容が消失する

### ISSUE THREAD

**Issue by ouroboros723** [totegamma/concurrent-web#319]
## Expected Behaviour / 期待した挙動
ホーム同時投稿モードがOFFかつ投稿先が未指定の状態ではPOSTボタンが押せない、もしくはエラーが表示される。
## Actural Behavior / 実際の挙動
ホーム同時投稿モードがOFFかつ投稿先が未指定の状態でもPOSTボタンが押せてしまう。
正常に投稿を行ったときと同じ挙動をするが、どこにも投稿されない。
## Steps to Reproduce / 再現方法
ホーム同時投稿モードがOFFかつ投稿先が未指定の状態で文字を入力し、POSTボタンを押す
## Additional Information / 追加情報
〇 投稿前
![image](https://github.com/totegamma/concurrent-web/assets/23020033/370f0003-4fab-48b8-af70-e0ee31522ed9)
〇 投稿後
![image](https://github.com/totegamma/concurrent-web/assets/23020033/a9d12373-4079-4fc7-bc98-682bc6091e1e)
〇 結果
![image](https://github.com/totegamma/concurrent-web/assets/23020033/59826384-6a4b-4208-a472-b943c9af1c36)

フォローしているストリームも一通り確認しましたが、どこにも投稿が見当たりませんでした。

〇 再現バージョン情報
buildTime: 2023/8/22 23:29:56
branch: concurrent
sha: 34cc5e1

※ もし仕様の場合はCloseしてください💦

**Comment by ouroboros723** [comment]
修正コミット準備中です。

**Comment by totegamma** [comment]
起票ありがとうございます！
これは「メッセージは作成されているがどこにも共有されていない」という状態ですね。
それはそれとしてたしかにこのvalidationはあったほうがいいですね！
個人的には空っぽで投稿したときと同様にenqueue snack barでお知らせするのがいいかな～と思いますがどうでしょうか！

https://github.com/totegamma/concurrent-web/blob/develop/src/components/Draft.tsx#L87-L90

**Comment by ouroboros723** [comment]
ご確認&修正いただきありがとうございます...!!!
自分も似たような実装で考えてました！（post() メソッドの外側でチェックする記述をしてしまっていましたが💦）
僕個人としてはこの修正で問題ないかと思います！

> これは「メッセージは作成されているがどこにも共有されていない」

この場合、宙ぶらりん（？）状態になっている投稿はどこかで確認できるのでしょうか...？

**Comment by totegamma** [comment]
あっあっ　上のコード引用は「中身が空の時投稿できない」の既存コードの例示でした！なのでまだ今回の修正は何もしてないです！　ぜひお願いできれば...🙏

**Comment by totegamma** [comment]
宙ぶらりんなメッセージは現状確認できる方法はないのですが、いずれは自己所有オブジェクト一覧は閲覧できるようにはしたいな〜とは思ってました！

**Comment by ouroboros723** [comment]
> あっあっ　上のコード引用は「中身が空の時投稿できない」の既存コードの例示でした！なのでまだ今回の修正は何もしてないです！　ぜひお願いできれば...🙏

すみません、スマホでコードチラ見してたので完全に勘違いしてました💦
わかりました！後ほどプルリク投げさせていただきます(/･ω･)/

**Comment by ouroboros723** [comment]
> 宙ぶらりんなメッセージは現状確認できる方法はないのですが、いずれは自己所有オブジェクト一覧は閲覧できるようにはしたいな〜とは思ってました！

なるほど、今後確認できるようになる予定なんですね👀
