### ISSUE TITLE
markdownのスタイルをいい感じにする

### ISSUE THREAD

**Issue by totegamma** [totegamma/concurrent-web#36]
今なんかやたら間隔がデカい

**Comment by jojo3926** [comment]
要素に適用されてるCSSのmarginがやけにでかいのでどうにかして直します

**Comment by jojo3926** [comment]
なんもわからなくなりました

**Comment by totegamma** [comment]
これはHeading要素を対応するMUIのTypography要素に置き換える設定を入れてあげるといいのかなと思ってます

**Comment by totegamma** [comment]
tweet.tsxの200行目からのところですね。p要素だけマッピングがありますが、これをh要素などにもそれぞれ適切にマッピングしてあげるといい感じになるかも？と思ってます！

**Comment by jojo3926** [comment]
意外と力技なんですね

**Comment by jojo3926** [comment]
![image](https://user-images.githubusercontent.com/13605108/236458790-283d13e9-d847-48f4-b185-2286b0742c1a.png)
Typographyにした後
![image](https://user-images.githubusercontent.com/13605108/236458295-fc827fba-be7b-4619-b9eb-2ae0f15d4a96.png)
する前

明らかにでかくなるのとフォントがちょっと変わる問題がありますがこれはなるべく変更前のものに寄せるようにしますか？

**Comment by totegamma** [comment]
試してみてくださりありがとうございます！素敵です

確かに、これは大きすぎですね...
基本的には、theme.tsにtypography用のテーマの記述を行うことで大きさを小さくすることになると思います。

ただ、md上の#1つの見出しを、typographyのどのvariantと対応付けるべきなのかというのは議論の余地があるかもしれません。
(例えば、ユーザーは平気で#1つのタグを使ってくると思いますが、慣習的にhtmlのh1タグは1つのhtmlページに1つしか配置しないので意図的にh2以下と対応付ける、など。)

**Comment by totegamma** [comment]
#57 で解決
