### ISSUE TITLE
Loading State 時の表示対応

### ISSUE THREAD

**Issue by SLAVR00** [totegamma/concurrent-web#92]
### 背景
現状Homeタブ等に遷移を行う際に読み込み中表示がないため
画面遷移にラグがあるように見えてしまっている

### 目的
- 画面単位またはメッセージ単位での Loading State を追加
  - 遷移表示の遅延を解消しUXを向上させる

**Comment by totegamma** [comment]
これ超ほしい～～～～～～～～メッセージ単位でghost表示したいかも～～～～って思ってました

**Comment by totegamma** [comment]
#15 でリストの表示をvirtualなやつにするので、そこと密に関係するかもなのでメモ
